# Generated by Django 2.1.5 on 2019-02-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190220_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadNnm',
            new_name='ReadNum',
        ),
    ]
