# Generated by Django 2.1.5 on 2019-02-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190220_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readnum',
            old_name='read_num',
            new_name='count',
        ),
    ]
